apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "xmrig.fullname" . }}
  labels:
    {{- include "xmrig.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  selector:
    matchLabels:
      {{- include "xmrig.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xmrig.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:v{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ./xmrig
            - --donate-level
            - '{{ .Values.poolDonationPercent }}'
            - --max-cpu-usage
            - '98'
            - --coin monero
            - -o
            - {{ .Values.pool }}
            - -u
            - {{ .Values.email }}
            - -p
            - {{ .Values.password }}
            - -k
            - --randomx-mode={{ .Values.randomxMode }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
